version: "3.9"

services:
  app:
    build: .
    container_name: bankcards-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcards
      SPRING_DATASOURCE_USERNAME: postgres-usr
      SPRING_DATASOURCE_PASSWORD:  123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGE_LOG:  classpath:db/migration/changelog-master.yml
      TOKEN_SIGNING_KEY: 7a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p
      ENCRYPTION_KEY: LCs0gcDY44IWSo61FjwH4L+Vgwm+oL+SsL4Gy68kPvs=
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bankcards-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: postgres-usr
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
