server:
  port: 8080

spring:
  application:
    name: bankcards

  datasource:
    url: ${BANKCARDS_DB_URL}
    username: ${BANKCARDS_DB_USERNAME}
    password: ${BANKCARDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/migration/changelog-master.yml