server:
  port: 8080

spring:
  application:
    name: bankcards

  datasource:
    url: ${BANKCARDS_DB_URL}
    username: ${BANKCARDS_DB_USERNAME}
    password: ${BANKCARDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    change-log: classpath:db/migration/changelog-master.yml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  expiration: 86400000

encryption:
  key: ${ENCRYPTION_KEY}